### ISSUE TITLE
Feat: Add some basic meta description tags to site for SEO

### ISSUE THREAD

**Issue by data-daddy-admin** [data-daddy-admin/portofino#10]
Not even sure if its done much anymore with googles changes but we can cook up some meta slogans to toss in the site header and tailor the SEO results.

![image](https://github.com/data-daddy-admin/portofino/assets/141653474/e57e713e-b5fc-422c-8aae-6ecc917b5e49)

**Comment by asfundb** [comment]
Feat Added: https://github.com/data-daddy-admin/portofino/commit/3212085cf97ecc29cba3ae99591b0f46e7567538
