### ISSUE TITLE
fix: Nav back home from login and download page not working

### ISSUE THREAD

**Issue by data-daddy-admin** [data-daddy-admin/portofino#6]
![image](https://github.com/data-daddy-admin/portofino/assets/141653474/b079cd1c-c752-4816-89da-1e3d7ab72dee)

Unable to navigate back to home page after user gets to the Login screen.

**Comment by data-daddy-admin** [comment]
Nav links back home not working on download and login page.

**Comment by asfundb** [comment]
Fixed: https://github.com/data-daddy-admin/portofino/commit/4fd0ffb0d42322b7199e8893cacce0fc83f54383
