### ISSUE TITLE
fix: landing page logo loading issue on certain browsers / platforms

### ISSUE THREAD

**Issue by data-daddy-admin** [data-daddy-admin/portofino#7]
![image](https://github.com/data-daddy-admin/portofino/assets/141653474/fa268ce9-5df5-49d3-9ddd-59be4d19c27c)

This might be a cache issue with me locally, but im getting this behavior on chrome, edge and on my Iphone.

The logo appears to load fine on my macbook.

**Comment by data-daddy-admin** [comment]
referencing this svg for logo
![image](https://github.com/data-daddy-admin/portofino/assets/141653474/9601a871-2332-4598-8c4e-6fb1e4f9d6f3)

**Comment by asfundb** [comment]
@data-daddy-admin SVGs, whilst they are higher quality for web have their own fonts that need. In this case, the font is a bit tricky to get consistent across all browsers/devices to hotswapped it for a png. 

fixed: https://github.com/data-daddy-admin/portofino/commit/c244c1ac32726ca7d64893b5fda36405be5fdcc3
