### ISSUE TITLE
fix: update browser tab data to display better marketing text. 

### ISSUE THREAD

**Issue by data-daddy-admin** [data-daddy-admin/portofino#9]
<img width="254" alt="image" src="https://github.com/data-daddy-admin/portofino/assets/141653474/82c14f1f-2e48-414b-bfb5-71434abcfbe0">

Schema example:
Data Daddy
Download - Data Daddy
Login - Data Daddy

or whatever is best practice is fine

**Comment by asfundb** [comment]
<img width="223" alt="Screenshot 2023-08-08 at 12 48 21" src="https://github.com/data-daddy-admin/portofino/assets/119081583/944e9f21-1fde-41b2-8f1d-08e524a8f695">
<img width="215" alt="Screenshot 2023-08-08 at 12 48 34" src="https://github.com/data-daddy-admin/portofino/assets/119081583/b244bde8-5a69-49dd-870d-925ac5d40766">
